# This file was generated by GoReleaser. DO NOT EDIT.
cask "fontget" do
  name "fontget"
  desc "A tiny, cross-platform CLI tool to install and manage fonts from the command line"
  homepage "https://github.com/Graphixa/FontGet"
  version "2.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fontget"

  on_macos do
    on_intel do
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_darwin_amd64.tar.gz"
      sha256 "f39b216f1bc402863b24b32300faaa482dfe5dcff34c0cd24bf7d6229e4a20fd"
    end
    on_arm do
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_darwin_arm64.tar.gz"
      sha256 "ca528364a1ac747f4d2369a0cd199dc91e562f5a9f690b0c7d87f810ba3031c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_linux_amd64.tar.gz"
      sha256 "f2898e891d84f1b19dfc70fd44331dbc7b73fe2f57c56509a259cf6dfeec70de"
    end
    on_arm do
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_linux_arm64.tar.gz"
      sha256 "1e309d1b4eecc58c3ed3722ec6d6a974ca373006e11042125cf89a1ff7016fae"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fontget"]
    end
  end

  # No zap stanza required
end
