# This file was generated by GoReleaser. DO NOT EDIT.
cask "fontget" do
  name "fontget"
  desc "A tiny, cross-platform CLI tool to install and manage fonts from the command line. Search for fonts, list installed fonts, install or remove fonts all from the CLI."
  homepage "https://github.com/Graphixa/FontGet"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fontget"

  on_macos do
    on_intel do
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_darwin_amd64.tar.gz"
      sha256 "68b5038e9d2362ff7a24b70df59bd4cc2ea8030167e5a1cbcf94d29849e2c7f6"
    end
    on_arm do
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_darwin_arm64.tar.gz"
      sha256 "b99e10fd240edd0a7d7a7a7aec7741d772370a671b5c537db3ab1a6e67a7fad5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_linux_amd64.tar.gz"
      sha256 "a877555975a909f57061cd767868a0d28d067ab0084420472a95e9f1ebc64c53"
    end
    on_arm do
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_linux_arm64.tar.gz"
      sha256 "5e8009b8cfe19ef77694b2e5c54a30b434529e6ef3775b50b2c6f8c723471299"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fontget"]
    end
  end

  # No zap stanza required
end
