# This file was generated by GoReleaser. DO NOT EDIT.
cask "fontget" do
  version "2.6.0"

  on_macos do
    on_intel do
      sha256 "713552a663f435a2af9f3ea6d8320ac4585525b49cc8d0705d2e761705ffa23b"
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85c651ebf10401a375d1f82e3fbadf4c37b4ff18b5952dbe7b643af102436eb5"
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "32f4564e299fcc40ab6b1183a3dbb32163cd0add145ea9af784f4e5dd89535a8"
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66995b4442d4116729936c364188c855ac377e0bc5fc1ac8743cd9718c4d6680"
      url "https://github.com/Graphixa/FontGet/releases/download/v#{version}/fontget_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fontget"
  desc "A tiny, cross-platform CLI tool to install and manage fonts from the command line. Search for fonts, list installed fonts, install or remove fonts all from the CLI."
  homepage "https://github.com/Graphixa/FontGet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fontget"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fontget"]
    end
  end

  # No zap stanza required

end
